/**
 * BM2 ecosystem config for the DOJCAD API server (CJS — maximally compatible).
 *
 * IMPORTANT: Run `bun run build` FIRST to generate the API bundle:
 *   bun install && bun run build
 *
 * This is a CommonJS config so `__dirname` (the repo root, where this file
 * lives) is always available — no reliance on ESM `import.meta` or cwd.
 *
 * Usage:
 *   bm2 start ecosystem.config.js
 *   bm2 save && bm2 startup install
 */
const path = require("node:path");

// __dirname = the directory this config file lives in = the repo root.
// This is ALWAYS correct, no matter what cwd bm2's daemon uses.
const repoRoot = __dirname;

module.exports = {
  apps: [
    {
      name: "dojcad-api",
      // Bun runs the bundled ESM output directly (generated by `bun run build`).
      // bootstrap-env.ts inside the bundle walks up to the repo root and
      // loads .env automatically.
      script: path.join(repoRoot, "artifacts", "api-server", "dist", "index.mjs"),
      // bm2 normally uses bun; set explicitly to be safe.
      interpreter: "bun",
      // Absolute cwd so the daemon runs from the repo root.
      cwd: repoRoot,
      // Fork mode, single instance. Production uses MongoDB Atlas (DATA_STORE=mongo).
      // Clustering would split in-process state — keep instances at 1.
      exec_mode: "fork",
      instances: 1,
      // Restart if it exceeds ~500MB or crashes repeatedly.
      max_memory_restart: "500M",
      max_restarts: 15,
      min_uptime: "10s",
      restart_delay: 5000,
      env: {
        NODE_ENV: "production",
        // GitHub/VPS uses MongoDB Atlas only — never local SQLite.
        DATA_STORE: "mongo",
        // Port the API listens on. nginx proxies /api here.
        API_PORT: "8080",
        // Frontend port is unused in production (nginx serves static files),
        // but Vite config reads it — keep it consistent.
        WEB_PORT: "5173",
      },
      // Heartbeat/health check — the API exposes /api/healthz.
      health_check_url: "http://127.0.0.1:8080/api/healthz",
    },
  ],
};